spring:
  redis:
    host: localhost
    port: 6379
    database: 0             # Redis DB index，預設是 0
    timeout: 5000ms         # 連線 timeout 時間
    lettuce:
      pool:
        max-active: 10      # 最多連線數
        max-idle: 5
        min-idle: 1
        max-wait: 5s
  jpa:
    hibernate:
      ddl-auto: update  # 可選 create / update / none
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/cclemon-health?allowPublicKeyRetrieval=true&serverTimezone=Asia/Taipei&useSSL=false
    username: root
    password: P@ssw0rd
    driverClassName: com.mysql.cj.jdbc.Driver
  kafka:
    bootstrap-servers: localhost:9093,localhost:9095,localhost:9097


logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.boot.autoconfigure: DEBUG

server:
  port: 8888
  tomcat:
    max-connections: 10000
    accept-count: 10000
    threads:
      max: 10000
      
management:
  endpoints:
    web:
      exposure:
        include: refresh

authorization-server:
  url: http://localhost:9000
cclemon-ui:
  url: http://127.0.0.1:5173
